export const Icon = {
  ADDRESS_CARD        :   0xf2bb,
  ARROW_LEFT          :   0xf060,
  BARCODE             :   0xf02a,
  BARS                :   0xf0c9,
  BELL                :   0xf0f3,
  BELL_SLASH          :   0xf1f6,
  BRIEFCASE           :   0xf0b1,
  BUILDING            :   0xf1ad,
  CALENDAR_ALT        :   0xf073,
  CALENDAR_PLUS       :   0xf271,
  CAMERA              :   0xf030,
  CAPSULES            :   0xf46b,
  CC_AMEX             :   0xf1f3,
  CC_MASTERCARD       :   0xf1f1,
  CC_VISA             :   0xf1f0,
  CHECK               :   0xf00c,
  CHECK_CIRCLE        :   0xf058,
  CHEVRON_DOWN        :   0xf078,
  CHEVRON_RIGHT       :   0xf054,
  CIRCLE              :   0xf111,
  CLIPBOARD_LIST      :   0xf46d,
  CLOCK               :   0xf017,
  COG                 :   0xf013,
  CROSSHAIRS          :   0xf05b,
  CREDIT_CARD         :   0xf09d,
  DOLLAR_SIGN         :   0xf155,
  DOT_CIRCLE          :   0xf192,
  EDIT                :   0xf044,
  ELLIPSIS_V          :   0xf142,
  ENVELOPE            :   0xf0e0,
  EXCLAMATION         :   0xf12a,
  EXCLAMATION_CIRCLE  :   0xf06a,
  FACEBOOK            :   0xf39e,
  FILTER              :   0xf0b0,
  FLASK               :   0xf0c3,
  GOOGLE              :   0xf1a0,
  HEADPHONES          :   0xf025,
  HOME                :   0xf015,
  HOSPITAL            :   0xf0f8,
  INDUSTRY            :   0xf275,
  MAP_MARKER_ALT      :   0xf3c5,
  MEDKIT              :   0xf0fa,
  MINUS               :   0xf068,
  MONEY_BILL_ALT      :   0xf3d1,
  PENCIL_ALT          :   0xf303,
  PHONE               :   0xf095,
  PILLS               :   0xf484,
  PLUS                :   0xf067,
  PRESCRIPTION_BOTTLE :   0xf486,
  PRODUCT_HUNT        :   0xf288,
  SAVE                :   0xf0c7,
  SEARCH              :   0xf002,
  SIGN_OUT_ALT        :   0xf2f5,
  SQUARE              :   0xf0c8,
  STAR                :   0xf005,
  SYNC_ALT            :   0xf2f1,
  TIMES               :   0xf00d,
  TOOTH               :   0xf5c9,
  TRASH               :   0xf1f8,
  USER                :   0xf007,
  USER_MD             :   0xf0f0,
  USERS               :   0xf0c0,
  WIFI                :   0xf1eb
  
}

export function getIcon(code) {
  return String.fromCharCode(code);
}